version: '3.7'

services:
  postgres:
    restart: always
    image: "postgres:13.3-alpine"
    command:
      - postgres
    ports:
      - 5432
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: bb_db
  app:
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      target: dev
    ports:
      - 8000:8000
    command: ['runserver']
    environment:
      DATABASE_URI: 'postgresql://testuser:testpassword@postgres:5432/bb_db'
    volumes:
      - ./assessment:/srv/app/assessment
  django-migrate:
    restart: on-failure
    depends_on:
      - postgres
    build:
      context: .
      target: dev
    command: ['migrate']
    environment:
      DATABASE_URI: 'postgresql://testuser:testpassword@postgres:5432/bb_db'
    volumes:
      - ./assessment:/srv/app/assessment
  collectstatic:
    restart: on-failure
    depends_on:
      - postgres
    build:
      context: .
      target: dev
    command: ['collectstatic']
    environment:
      DATABASE_URI: 'postgresql://testuser:testpassword@postgres:5432/bb_db'
    volumes:
      - ./assessment:/srv/app/assessment
