# Generated by Django 3.2.10 on 2023-04-22 02:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('modified_at', models.DateTimeField(auto_created=True, auto_now=True, db_index=True, verbose_name='last modified at')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.UUID('5b22b1ff-10fc-478c-a146-8ac011322c01'), editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.CharField(default='f6a7d16ce55b10ee42be91d7adb7939065a8d83f', max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('modified_at', models.DateTimeField(auto_created=True, auto_now=True, db_index=True, verbose_name='last modified at')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.UUID('5b22b1ff-10fc-478c-a146-8ac011322c01'), editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(default='e8f4ca349f7561e1bbf8362275aebf6c7cdeabe1', max_length=255, unique=True)),
                ('data', models.JSONField(blank=True, default=list, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='batches.batch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
