# Generated by Django 3.2.10 on 2023-04-22 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name_plural': 'Objects'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.CharField(default='ef9749e2981b67f709e9b2ac21cccf6a42352106', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6b810919-930a-4a88-bd56-e1e2adc74eca'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6b810919-930a-4a88-bd56-e1e2adc74eca'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_id',
            field=models.CharField(default='7e3fa4ed37cf34d82dbbe5116cb2e7deede2a754', max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('object_id', 'batch')},
        ),
    ]
