# Generated by Django 3.2.10 on 2023-04-22 03:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_auto_20230422_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.CharField(default='106ac21ff0f72f928ab0bdd4ad3bb548da4d3131', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_id',
            field=models.CharField(default='c769430068bdefa0d1a001581acdabd062dd12cb', max_length=255, unique=True),
        ),
    ]
