#!/bin/bash
# shellcheck disable=SC1090
set -Eeu -o pipefail

# Make sure we are running this from the directory with the compose file(s)
SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
cd "${SCRIPT_DIR}" || exit
cd "../" || exit

docker-compose build
docker-compose run --rm app python manage.py migrate
docker-compose up -d
